name: CI
on: [push, pull_request]

jobs:
  pipeline-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v1
      - name: Run pipeline
        run: |
          nextflow run ${GITHUB_WORKSPACE} --help 